<?php
class Langue
{
    private static $traductions = [];
    private static $langue = 'en';
    private static $langues_dispo = ['en', 'sq', 'vi'];

    public static function init()
    {
        if (isset($_GET['lang']) && in_array($_GET['lang'], self::$langues_dispo)) {
            $_SESSION['lang'] = $_GET['lang'];
        }
        self::$langue = $_SESSION['lang'] ?? 'en';
        self::charger();
    }

    public static function getLang()
    {
        return self::$langue;
    }

    public static function getAll()
    {
        return self::$langues_dispo;
    }

    private static function charger()
    {
        $en = [
            'site_name' => 'Crilay',
            'site_slogan' => 'Where generations meet through art.',
            'home' => 'Home',
            'signup' => 'Sign up',
            'login' => 'Sign in',
            'logout' => 'Sign out',
            'back_public' => 'View site',
            'search' => 'Explore',
            'messages' => 'Messages',
            'agenda' => 'Calendar',
            'profile' => 'My Profile',
            'friends' => 'My Network',
            'feed' => 'Feed',

            'hero_title' => '<em>Share</em> your art. <em>Meet</em> your community.',
            'hero_subtitle' => 'Crilay is the intergenerational social network where artists of all ages share their creative techniques and know-how beyond borders.',
            'discover_video' => 'Discover Crilay in video',
            'why_title' => 'Why join Crilay?',
            'why_1_title' => 'Intergenerational exchange',
            'why_1_desc' => 'Learn watercolour from a senior, or teach someone digital painting. Every generation has its own technique to share.',
            'why_2_title' => '37 artistic disciplines',
            'why_2_desc' => 'Painting, sculpture, manga, animation, pottery, origami... All forms of art await you.',
            'why_3_title' => 'Global community',
            'why_3_desc' => 'Meet artists of all ages and countries, in 3 languages.',
            'how_title' => 'Three steps, that\'s all',
            'how_1_title' => 'Create your profile',
            'how_1_desc' => 'Sign up and choose your artistic disciplines from 37 categories.',
            'how_2_title' => 'Find artists',
            'how_2_desc' => 'Search by discipline, language or location on the interactive map.',
            'how_3_title' => 'Create together',
            'how_3_desc' => 'Send messages, plan creative sessions online and share your techniques.',
            'join_cta' => 'Your artistic community is waiting',
            'member_count_text' => 'Free, no ads, no algorithm. Just real artists who share.',

            'register_title' => 'Join Crilay',
            'pseudo' => 'Username',
            'email' => 'Email address',
            'password' => 'Password',
            'password_confirm' => 'Confirm password',
            'spoken_languages' => 'Languages spoken',
            'nationality' => 'Nationality',
            'birthdate' => 'Date of birth',
            'city' => 'City',
            'bio' => 'About me',
            'experiences_texte' => 'Describe your artistic journey',
            'experiences_placeholder' => 'E.g.: I\'ve been painting watercolours for 30 years, I\'d like to learn digital painting, I can teach perspective...',
            'photo' => 'Profile photo',
            'select_tags' => 'Your artistic disciplines',
            'tagcat_plastic' => 'Plastic & Traditional Arts',
            'tagcat_narrative' => 'Narrative & Sequential Arts',
            'tagcat_design' => 'Design & Digital Arts',
            'tagcat_craft' => 'Crafts & Mixed Techniques',
            'tagcat_visual' => 'Visual & Optical Arts',
            'tagsub_painting' => 'Painting',
            'tagsub_drawing' => 'Drawing & Illustration',
            'tagsub_sculpture' => 'Sculpture & Volume',
            'tagsub_graphic_narr' => 'Graphic Narration',
            'tagsub_animation' => 'Animation',
            'tagsub_graphic_design' => 'Graphic Design',
            'tagsub_technical' => 'Technical Design',
            'tagsub_paper' => 'Paper Work',
            'tagsub_textile' => 'Textile & Handmade Arts',
            'tagsub_assembly' => 'Assembly & Printing',
            'tagsub_captured' => 'Captured Image',
            'tagsub_conceptual' => 'Conceptual Styles',
            'accept_cgu' => 'I accept the terms of use',
            'register_btn' => 'Create my account',
            'next' => 'Next',
            'previous' => 'Previous',
            'step_account' => 'Account',
            'step_profile' => 'Profile',
            'step_finish' => 'Finish',
            'already_account' => 'Already have an account?',

            'login_title' => 'Sign in',
            'login_btn' => 'Sign in',
            'no_account' => 'Don\'t have an account yet?',

            'edit_profile' => 'Edit profile',
            'save' => 'Save',
            'cancel' => 'Cancel',
            'member_since' => 'Member since',
            'age' => 'Age',
            'skills' => 'Artistic disciplines',
            'years_old' => 'years old',
            'experiences_section' => 'My artistic journey',

            'search_title' => 'Explore artists',
            'search_placeholder' => 'Search for an artist...',
            'filter_language' => 'Filter by language',
            'filter_tag' => 'Filter by discipline',
            'all_languages' => 'All languages',
            'all_tags' => 'All disciplines',
            'no_results' => 'No results found.',
            'gallery' => 'Gallery',
            'delete' => 'Delete',
            'confirm_delete' => 'Are you sure you want to delete this?',
            'delete_image' => 'Delete image',
            'follow' => 'Follow',
            'following' => 'Following',
            'followers' => 'Followers',
            'no_followers' => 'No followers yet.',
            'text_posts' => 'Text Posts',
            'view_profile' => 'View profile',
            'map_view' => 'Map view',
            'list_view' => 'List view',

            'add_friend' => 'Connect',
            'pending' => 'Pending',
            'accept' => 'Accept',
            'decline' => 'Decline',
            'remove_friend' => 'Remove from network',
            'friend_requests' => 'Connection requests',
            'no_friends' => 'Your network is empty. Start exploring artists!',

            'send_message' => 'Send a message',
            'type_message' => 'Write your message...',
            'send' => 'Send',
            'conversations' => 'My conversations',
            'no_messages' => 'No conversations yet.',
            'invitation_sent' => 'Connection request sent with your message.',
            'must_connect_first' => 'You must be connected to exchange more. Please wait for approval.',
            'new_conversation' => 'New conversation',

            'feed_title' => 'Feed',
            'write_post' => 'What\'s new in your studio?',
            'publish' => 'Post',
            'no_posts' => 'No posts yet. Be the first!',
            'new_members' => 'Friend suggestions',
            'upcoming_events' => 'Upcoming events',

            'agenda_title' => 'My Calendar',
            'create_event' => 'New event',
            'event_title' => 'Title',
            'event_desc' => 'Description',
            'event_start' => 'Start',
            'event_end' => 'End',
            'event_type' => 'Event type',
            'event_private' => 'Private',
            'event_shared' => 'Shared',
            'event_public' => 'Public (visible to your network)',
            'event_participants' => 'Participants',
            'event_add_participant' => 'Add a participant',
            'event_busy' => 'Busy',
            'no_events' => 'No events planned.',
            'delete_event' => 'Delete',
            'event_pending' => 'Pending invitations',
            'event_accepted' => 'Accepted',
            'event_refused' => 'Declined',
            'accept_event' => 'Accept',
            'decline_event' => 'Decline',

            'nav_explore' => 'Explore',
            'nav_learn' => 'Learn',
            'nav_community' => 'Community',
            'nav_profile' => 'Profile',
            'nav_about' => 'About',

            'tutorials' => 'Tutorials',
            'tutorials_intro' => 'Discover artistic tutorials shared by community members.',
            'tutorials_ex1_title' => 'Watercolour & Painting',
            'tutorials_ex1_desc' => 'Learn painting techniques passed down between generations.',
            'tutorials_ex2_title' => 'Digital Art',
            'tutorials_ex2_desc' => 'Digital painting, illustration, motion design: young artists share their tools.',
            'tutorials_ex3_title' => 'Crafts & Creation',
            'tutorials_ex3_desc' => 'Pottery, origami, textiles: craft skills have no age.',
            'workshops' => 'Workshops',
            'workshops_intro' => 'Join creative online workshops organised by the community.',
            'workshops_ex1_title' => 'Live sketch session',
            'workshops_ex1_desc' => 'Each week, an artist leads a live drawing session.',
            'workshops_ex2_title' => 'Art critique circle',
            'workshops_ex2_desc' => 'Present your creations and receive feedback from all ages.',
            'workshops_ex3_title' => 'Intergenerational masterclass',
            'workshops_ex3_desc' => 'Experienced artists pass on their techniques to beginners.',
            'resources' => 'Resources',
            'resources_intro' => 'Guides, tools and artistic references shared by the community.',
            'resources_ex1_title' => 'Technical guides',
            'resources_ex1_desc' => 'Practical sheets to progress in each discipline.',
            'resources_ex2_title' => 'Recommended tools',
            'resources_ex2_desc' => 'Software, materials and platforms recommended by the community.',
            'resources_ex3_title' => 'Inspiration gallery',
            'resources_ex3_desc' => 'Works, articles and references shared between artists.',

            'forum' => 'Forum',
            'forum_intro' => 'Discuss with the community on all topics.',
            'events' => 'Events',
            'showcases' => 'Showcases',
            'showcases_intro' => 'Discover creations and works from members.',
            'coming_soon' => 'This feature is coming soon! Stay connected.',

            'dashboard' => 'Dashboard',
            'portfolio' => 'Portfolio',
            'portfolio_hint' => 'Your portfolio showcases your disciplines and artistic journey to other members. Enrich it to attract more connections!',
            'settings' => 'Settings',

            'team' => 'The Team',
            'team_intro' => 'Crilay is made by an international team of students.',
            'team_dev_title' => 'Development',
            'team_dev_desc' => 'Design and development of the web platform.',
            'team_design_title' => 'Design & Graphics',
            'team_design_desc' => 'Visual identity, interfaces and user experience.',
            'team_comm_title' => 'Communication',
            'team_comm_desc' => 'Communication strategy and project promotion.',
            'contact' => 'Contact',
            'contact_intro' => 'Got a question? Get in touch!',
            'contact_email_label' => 'Email',
            'contact_discord' => 'Also join us on our Discord server.',

            'about' => 'About',
            'faq' => 'FAQ',
            'legal' => 'Legal notice',
            'cgu' => 'Terms of use',
            'privacy' => 'Privacy policy',
            'footer_copy' => '© 2026 Crilay Made with love for artists of all ages.',

            'about_title' => 'About Crilay',
            'about_text' => 'Crilay is an intergenerational social network dedicated to art and creation. It enables artists of all ages, countries and cultures to meet online and share their creative techniques and know-how. Our mission: bringing generations together through artistic sharing.',
            'faq_title' => 'Frequently asked questions',
            'legal_title' => 'Legal notice',
            'legal_text' => 'Crilay is an educational project created as part of the IOBC 2026 International Seminar. Publisher: Crilay Team IUT de Bobigny, Université Sorbonne Paris Nord. Hosting: LAMP server at IUT de Bobigny.',
            'cgu_title' => 'Terms of use',
            'cgu_text' => 'By using Crilay, you agree to: respect other users regardless of their age, culture or origin; not publish hateful, racist, sexist or violent content; comply with your country\'s legislation regarding shared content; use the platform in a spirit of intergenerational sharing. Any violation may result in account suspension. Discussions and shared content must follow community guidelines.',
            'privacy_title' => 'Privacy policy',
            'privacy_text' => 'In accordance with the General Data Protection Regulation (GDPR), your personal data is stored securely and never shared with third parties. Email addresses are never visible to other users. The internal messaging system allows you to communicate without revealing your personal details. You can request deletion of your data at any time by contacting us.',

            'error_pseudo_taken' => 'This username is already taken.',
            'error_email_taken' => 'This email is already in use.',
            'error_password_mismatch' => 'Passwords do not match.',
            'error_password_short' => 'Password must be at least 8 characters.',
            'error_cgu' => 'You must accept the terms of use.',
            'error_login' => 'Invalid credentials.',
            'error_fields' => 'Please fill in all required fields.',
            'success_register' => 'Welcome to Crilay! Sign in to join the community.',
            'success_profile' => 'Profile updated successfully.',
        ];

        $sq = [
            'site_name' => 'Crilay',
            'site_slogan' => 'Brezat takohen këtu.',
            'home' => 'Kryefaqja',
            'signup' => 'Regjistrohu',
            'login' => 'Hyr',
            'logout' => 'Dil',
            'back_public' => 'Shiko faqen',
            'search' => 'Eksploro',
            'messages' => 'Mesazhet',
            'agenda' => 'Axhenda',
            'profile' => 'Profili im',
            'friends' => 'Rrjeti im',
            'feed' => 'Lajmet',

            'hero_title' => 'Ndani artin tuaj, lidhni brezat',
            'hero_subtitle' => 'Crilay është rrjeti social ku artistë të të gjitha moshave shkëmbejnë teknikat e tyre kreative përtej kufijve.',
            'discover_video' => 'Zbuloni Crilay në video',
            'why_title' => 'Pse të bashkoheni me Crilay?',
            'why_1_title' => 'Shkëmbim ndërbrezash',
            'why_1_desc' => 'Mësoni akuarelin me një artist të moshuar, ose ndani dixhitalin me dikë. Çdo brez ka teknikën e vet.',
            'why_2_title' => '37 disiplina artistike',
            'why_2_desc' => 'Pikturë, skulpturë, manga, animacion, poçari, origami... Të gjitha format e artit ju presin.',
            'why_3_title' => 'Komunitet botëror',
            'why_3_desc' => 'Takoni artistë të të gjitha moshave dhe vendeve, në 3 gjuhë.',
            'how_title' => 'Si funksionon?',
            'how_1_title' => 'Krijoni profilin tuaj',
            'how_1_desc' => 'Regjistrohuni dhe zgjidhni disiplinat tuaja artistike mes 37 kategorive.',
            'how_2_title' => 'Gjeni artistë',
            'how_2_desc' => 'Kërkoni sipas disiplinës, gjuhës ose vendndodhjes në hartën interaktive.',
            'how_3_title' => 'Shkëmbeni dhe krijoni',
            'how_3_desc' => 'Dërgoni mesazhe, planifikoni sesione kreative online dhe ndani teknikat tuaja.',
            'join_cta' => 'Bashkohuni me komunitetin',
            'member_count_text' => 'Artistë të të gjitha brezave ju presin.',

            'register_title' => 'Bashkohuni me Crilay',
            'pseudo' => 'Pseudonimi',
            'email' => 'Adresa email',
            'password' => 'Fjalëkalimi',
            'password_confirm' => 'Konfirmo fjalëkalimin',
            'spoken_languages' => 'Gjuhët e folura',
            'nationality' => 'Kombësia',
            'birthdate' => 'Data e lindjes',
            'city' => 'Qyteti',
            'bio' => 'Rreth meje',
            'experiences_texte' => 'Përshkruani rrugëtimin tuaj artistik',
            'experiences_placeholder' => 'Psh: Pikturoj me akuarel prej 30 vitesh, dua të mësoj pikturën dixhitale, mund të mësoj perspektivën...',
            'photo' => 'Foto e profilit',
            'select_tags' => 'Disiplinat tuaja artistike',
            'tagcat_plastic' => 'Artet Plastike dhe Tradicionale',
            'tagcat_narrative' => 'Artet Narrative dhe Sekuenciale',
            'tagcat_design' => 'Dizajni dhe Artet Dixhitale',
            'tagcat_craft' => 'Artizanati dhe Teknikat e Përziera',
            'tagcat_visual' => 'Artet Vizuale dhe Optike',
            'tagsub_painting' => 'Pikturë',
            'tagsub_drawing' => 'Vizatim dhe Ilustrim',
            'tagsub_sculpture' => 'Skulpturë dhe Volum',
            'tagsub_graphic_narr' => 'Narracioni Grafik',
            'tagsub_animation' => 'Animacion',
            'tagsub_graphic_design' => 'Dizajn Grafik',
            'tagsub_technical' => 'Dizajn Teknik',
            'tagsub_paper' => 'Punë me Letër',
            'tagsub_textile' => 'Arte Tekstile dhe Manuale',
            'tagsub_assembly' => 'Montazh dhe Shtypje',
            'tagsub_captured' => 'Imazh i Kapur',
            'tagsub_conceptual' => 'Stile Konceptuale',
            'accept_cgu' => 'Pranoj kushtet e përgjithshme të përdorimit',
            'register_btn' => 'Krijo llogarinë time',
            'next' => 'Tjetër',
            'previous' => 'Mbrapa',
            'step_account' => 'Llogaria',
            'step_profile' => 'Profili',
            'step_finish' => 'Përfundo',
            'already_account' => 'Keni tashmë një llogari?',

            'login_title' => 'Hyrje',
            'login_btn' => 'Hyr',
            'no_account' => 'Nuk keni ende llogari?',

            'edit_profile' => 'Modifiko profilin',
            'save' => 'Ruaj',
            'cancel' => 'Anulo',
            'member_since' => 'Anëtar që nga',
            'age' => 'Mosha',
            'skills' => 'Disiplinat artistike',
            'years_old' => 'vjeç',
            'experiences_section' => 'Rrugëtimi im artistik',

            'search_title' => 'Eksploroni komunitetin',
            'search_placeholder' => 'Kërkoni një person...',
            'filter_language' => 'Filtro sipas gjuhës',
            'filter_tag' => 'Filtro sipas aftësisë',
            'all_languages' => 'Të gjitha gjuhët',
            'all_tags' => 'Të gjitha aftësitë',
            'no_results' => 'Asnjë rezultat.',
            'gallery' => 'Galeria',
            'delete' => 'Fshi',
            'confirm_delete' => 'A jeni i sigurt që doni ta fshini?',
            'delete_image' => 'Fshi imazhin',
            'follow' => 'Ndiq',
            'following' => 'Duke ndjekur',
            'followers' => 'Ndjekës',
            'no_followers' => 'Asnjë ndjekës ende.',
            'text_posts' => 'Postime Tekst',
            'view_profile' => 'Shiko profilin',
            'map_view' => 'Pamja e hartës',
            'list_view' => 'Pamja e listës',

            'add_friend' => 'Lidhu',
            'pending' => 'Në pritje',
            'accept' => 'Prano',
            'decline' => 'Refuzo',
            'remove_friend' => 'Hiq nga rrjeti',
            'friend_requests' => 'Kërkesat e lidhjes',
            'no_friends' => 'Rrjeti juaj është bosh. Eksploroni komunitetin!',

            'send_message' => 'Dërgo një mesazh',
            'type_message' => 'Shkruani mesazhin tuaj...',
            'send' => 'Dërgo',
            'conversations' => 'Bisedat e mia',
            'no_messages' => 'Asnjë bisedë për momentin.',
            'invitation_sent' => 'Kërkesa e lidhjes u dërgua me mesazhin tuaj.',
            'must_connect_first' => 'Duhet të jeni të lidhur për të shkëmbyer më shumë. Prisni validimin.',
            'new_conversation' => 'Bisedë e re',

            'feed_title' => 'Lajmet',
            'write_post' => 'Ndani diçka me komunitetin...',
            'publish' => 'Publiko',
            'no_posts' => 'Asnjë publikim ende. Jini i pari!',
            'new_members' => 'Sugjerime miqsh',
            'upcoming_events' => 'Ngjarjet e ardhshme',

            'agenda_title' => 'Axhenda ime',
            'create_event' => 'Krijo një ngjarje',
            'event_title' => 'Titulli',
            'event_desc' => 'Përshkrimi',
            'event_start' => 'Fillimi',
            'event_end' => 'Fundi',
            'event_type' => 'Lloji i ngjarjes',
            'event_private' => 'Private',
            'event_shared' => 'E ndarë',
            'event_public' => 'Publike (e dukshme nga rrjeti)',
            'event_participants' => 'Pjesëmarrësit',
            'event_add_participant' => 'Shto një pjesëmarrës',
            'event_busy' => 'I zënë',
            'no_events' => 'Asnjë ngjarje e planifikuar.',
            'delete_event' => 'Fshi',
            'event_pending' => 'Ftesat në pritje',
            'event_accepted' => 'Pranuar',
            'event_refused' => 'Refuzuar',
            'accept_event' => 'Prano',
            'decline_event' => 'Refuzo',

            'nav_explore' => 'Eksploro',
            'nav_learn' => 'Mëso',
            'nav_community' => 'Komuniteti',
            'nav_profile' => 'Profili',
            'nav_about' => 'Rreth nesh',

            'tutorials' => 'Tutoriale',
            'tutorials_intro' => 'Zbuloni tutorialet artistike të ndara nga anëtarët e komunitetit.',
            'tutorials_ex1_title' => 'Akuarel & Pikturë',
            'tutorials_ex1_desc' => 'Mësoni teknikat e pikturës të trashëguara mes brezave.',
            'tutorials_ex2_title' => 'Art dixhital',
            'tutorials_ex2_desc' => 'Pikturë dixhitale, ilustrim, motion design: artistët e rinj ndajnë mjetet e tyre.',
            'tutorials_ex3_title' => 'Artizanat & Krijim',
            'tutorials_ex3_desc' => 'Poçari, origami, tekstil: aftësitë artizanale nuk kanë moshë.',
            'workshops' => 'Punëtori',
            'workshops_intro' => 'Merrni pjesë në punëtori kreative online të organizuara nga komuniteti.',
            'workshops_ex1_title' => 'Punëtori skicimi në drejtpërdrejt',
            'workshops_ex1_desc' => 'Çdo javë, një artist animon një sesion vizatimi në drejtpërdrejt.',
            'workshops_ex2_title' => 'Rreth kritikës artistike',
            'workshops_ex2_desc' => 'Prezantoni krijimet tuaja dhe merrni komente nga të gjitha moshat.',
            'workshops_ex3_title' => 'Masterclass ndërbrezash',
            'workshops_ex3_desc' => 'Artistë me përvojë transmetojnë teknikat e tyre fillestarëve.',
            'resources' => 'Burime',
            'resources_intro' => 'Udhëzues, mjete dhe referenca artistike nga komuniteti.',
            'resources_ex1_title' => 'Udhëzues teknikë',
            'resources_ex1_desc' => 'Fisha praktike për të përparuar në çdo disiplinë.',
            'resources_ex2_title' => 'Mjete të rekomanduara',
            'resources_ex2_desc' => 'Software, materiale dhe platforma të rekomanduara.',
            'resources_ex3_title' => 'Galeri frymëzimi',
            'resources_ex3_desc' => 'Vepra, artikuj dhe referenca të ndara mes artistëve.',

            'forum' => 'Forumi',
            'forum_intro' => 'Shkëmbeni me komunitetin për të gjitha temat.',
            'events' => 'Ngjarjet',
            'showcases' => 'Vitrinat',
            'showcases_intro' => 'Zbuloni realizimet dhe ndarjet e anëtarëve.',
            'coming_soon' => 'Kjo veçori vjen së shpejti! Qëndroni të lidhur.',

            'dashboard' => 'Paneli',
            'portfolio' => 'Portfoli',
            'portfolio_hint' => 'Portfoli juaj prezanton aftësitë dhe përvojat tuaja anëtarëve të tjerë. Pasuroni profilin tuaj!',
            'settings' => 'Cilësimet',

            'team' => 'Ekipi',
            'team_intro' => 'Crilay realizohet nga një ekip ndërkombëtar studentësh.',
            'team_dev_title' => 'Zhvillim',
            'team_dev_desc' => 'Konceptimi dhe zhvillimi i platformës web.',
            'team_design_title' => 'Dizajn & Grafikë',
            'team_design_desc' => 'Identiteti vizual, ndërfaqet dhe përvoja e përdoruesit.',
            'team_comm_title' => 'Komunikim',
            'team_comm_desc' => 'Strategjia e komunikimit dhe promovimi i projektit.',
            'contact' => 'Kontakt',
            'contact_intro' => 'Keni pyetje? Na kontaktoni!',
            'contact_email_label' => 'Email',
            'contact_discord' => 'Na bashkohuni gjithashtu në serverin tonë Discord.',

            'about' => 'Rreth nesh',
            'faq' => 'Pyetje',
            'legal' => 'Informacione ligjore',
            'cgu' => 'Kushtet e Përgjithshme',
            'privacy' => 'Politika e privatësisë',
            'footer_copy' => '© 2026 Crilay. Të gjitha të drejtat e rezervuara.',

            'about_title' => 'Rreth Crilay',
            'about_text' => 'Crilay është një rrjet social ndërbrezash që lejon personat e të gjitha moshave, vendeve dhe kulturave të takohen online për të shkëmbyer aftësi dhe përvoja jete. Misioni ynë: t\'i afroj brezat përmes ndarjes së njohurive.',
            'faq_title' => 'Pyetje të shpeshta',
            'legal_title' => 'Informacione ligjore',
            'legal_text' => 'Crilay është një projekt edukativ i realizuar në kuadrin e Seminarit Ndërkombëtar IOBC 2026. Botues: Ekipi Crilay IUT de Bobigny, Université Sorbonne Paris Nord.',
            'cgu_title' => 'Kushtet e Përgjithshme të Përdorimit',
            'cgu_text' => 'Duke përdorur Crilay, angazhoheni: të respektoni përdoruesit e tjerë pavarësisht moshës, kulturës apo origjinës; të mos publikoni përmbajtje urrejtjeje, raciste, seksiste apo të dhunshme; të respektoni legjislacionin e vendit tuaj; ta përdorni platformën në frymën e ndarjes ndërbrezash.',
            'privacy_title' => 'Politika e privatësisë',
            'privacy_text' => 'Në përputhje me GDPR, të dhënat tuaja personale ruhen në mënyrë të sigurt dhe nuk ndahen kurrë me palë të treta. Adresat email nuk janë kurrë të dukshme për përdoruesit e tjerë.',

            'error_pseudo_taken' => 'Ky pseudonim është i zënë.',
            'error_email_taken' => 'Ky email është tashmë i përdorur.',
            'error_password_mismatch' => 'Fjalëkalimet nuk përputhen.',
            'error_password_short' => 'Fjalëkalimi duhet të ketë të paktën 8 karaktere.',
            'error_cgu' => 'Duhet të pranoni kushtet e përdorimit.',
            'error_login' => 'Kredenciale të gabuara.',
            'error_fields' => 'Ju lutem plotësoni të gjitha fushat e detyrueshme.',
            'success_register' => 'Mirë se vini në Crilay! Hyni për t\'u bashkuar me komunitetin.',
            'success_profile' => 'Profili u përditësua me sukses.',
        ];

        $vi = [
            'site_name' => 'Crilay',
            'site_slogan' => 'Nơi các thế hệ gặp nhau.',
            'home' => 'Trang chủ',
            'signup' => 'Đăng ký',
            'login' => 'Đăng nhập',
            'logout' => 'Đăng xuất',
            'back_public' => 'Xem trang',
            'search' => 'Khám phá',
            'messages' => 'Tin nhắn',
            'agenda' => 'Lịch',
            'profile' => 'Hồ sơ của tôi',
            'friends' => 'Mạng lưới',
            'feed' => 'Bảng tin',

            'hero_title' => 'Chia sẻ nghệ thuật, kết nối thế hệ',
            'hero_subtitle' => 'Crilay là mạng xã hội nơi nghệ sĩ mọi lứa tuổi trao đổi kỹ thuật sáng tạo vượt qua mọi biên giới.',
            'discover_video' => 'Khám phá Crilay qua video',
            'why_title' => 'Tại sao tham gia Crilay?',
            'why_1_title' => 'Trao đổi liên thế hệ',
            'why_1_desc' => 'Học vẽ màu nước với nghệ sĩ lớn tuổi, hoặc chia sẻ vẽ kỹ thuật số. Mỗi thế hệ có kỹ thuật riêng.',
            'why_2_title' => '37 bộ môn nghệ thuật',
            'why_2_desc' => 'Hội họa, điêu khắc, manga, hoạt hình, gốm sứ, origami... Mọi hình thức nghệ thuật đang chờ bạn.',
            'why_3_title' => 'Cộng đồng toàn cầu',
            'why_3_desc' => 'Gặp gỡ nghệ sĩ mọi lứa tuổi và mọi quốc gia, bằng 3 ngôn ngữ.',
            'how_title' => 'Cách thức hoạt động?',
            'how_1_title' => 'Tạo hồ sơ',
            'how_1_desc' => 'Đăng ký và chọn bộ môn nghệ thuật trong 37 danh mục.',
            'how_2_title' => 'Tìm nghệ sĩ',
            'how_2_desc' => 'Tìm kiếm theo bộ môn, ngôn ngữ hoặc vị trí trên bản đồ tương tác.',
            'how_3_title' => 'Trao đổi và sáng tạo',
            'how_3_desc' => 'Gửi tin nhắn, lên lịch phiên sáng tạo trực tuyến và chia sẻ kỹ thuật.',
            'join_cta' => 'Tham gia cộng đồng',
            'member_count_text' => 'Nghệ sĩ mọi thế hệ đang chờ bạn.',

            'register_title' => 'Tham gia Crilay',
            'pseudo' => 'Biệt danh',
            'email' => 'Địa chỉ email',
            'password' => 'Mật khẩu',
            'password_confirm' => 'Xác nhận mật khẩu',
            'spoken_languages' => 'Ngôn ngữ sử dụng',
            'nationality' => 'Quốc tịch',
            'birthdate' => 'Ngày sinh',
            'city' => 'Thành phố',
            'bio' => 'Giới thiệu bản thân',
            'experiences_texte' => 'Mô tả hành trình nghệ thuật của bạn',
            'experiences_placeholder' => 'VD: Tôi vẽ màu nước 30 năm, muốn học vẽ kỹ thuật số, có thể dạy phối cảnh...',
            'photo' => 'Ảnh đại diện',
            'select_tags' => 'Bộ môn nghệ thuật của bạn',
            'tagcat_plastic' => 'Nghệ thuật Tạo hình và Truyền thống',
            'tagcat_narrative' => 'Nghệ thuật Tường thuật và Tuần tự',
            'tagcat_design' => 'Thiết kế và Nghệ thuật Số',
            'tagcat_craft' => 'Thủ công và Kỹ thuật Hỗn hợp',
            'tagcat_visual' => 'Nghệ thuật Thị giác và Quang học',
            'tagsub_painting' => 'Hội họa',
            'tagsub_drawing' => 'Vẽ và Minh họa',
            'tagsub_sculpture' => 'Điêu khắc và Khối',
            'tagsub_graphic_narr' => 'Kể chuyện bằng hình',
            'tagsub_animation' => 'Hoạt hình',
            'tagsub_graphic_design' => 'Thiết kế Đồ họa',
            'tagsub_technical' => 'Thiết kế Kỹ thuật',
            'tagsub_paper' => 'Nghệ thuật Giấy',
            'tagsub_textile' => 'Dệt may và Thủ công',
            'tagsub_assembly' => 'Ghép và In ấn',
            'tagsub_captured' => 'Hình ảnh Chụp',
            'tagsub_conceptual' => 'Phong cách Ý niệm',
            'accept_cgu' => 'Tôi chấp nhận điều khoản sử dụng',
            'register_btn' => 'Tạo tài khoản',
            'next' => 'Tiếp theo',
            'previous' => 'Quay lại',
            'step_account' => 'Tài khoản',
            'step_profile' => 'Hồ sơ',
            'step_finish' => 'Hoàn tất',
            'already_account' => 'Đã có tài khoản?',

            'login_title' => 'Đăng nhập',
            'login_btn' => 'Đăng nhập',
            'no_account' => 'Chưa có tài khoản?',

            'edit_profile' => 'Chỉnh sửa hồ sơ',
            'save' => 'Lưu',
            'cancel' => 'Hủy',
            'member_since' => 'Thành viên từ',
            'age' => 'Tuổi',
            'skills' => 'Bộ môn nghệ thuật',
            'years_old' => 'tuổi',
            'experiences_section' => 'Hành trình nghệ thuật',

            'search_title' => 'Khám phá cộng đồng',
            'search_placeholder' => 'Tìm một người...',
            'filter_language' => 'Lọc theo ngôn ngữ',
            'filter_tag' => 'Lọc theo kỹ năng',
            'all_languages' => 'Tất cả ngôn ngữ',
            'all_tags' => 'Tất cả kỹ năng',
            'no_results' => 'Không tìm thấy kết quả.',
            'gallery' => 'Thư viện',
            'delete' => 'Xóa',
            'confirm_delete' => 'Bạn có chắc muốn xóa không?',
            'delete_image' => 'Xóa hình ảnh',
            'follow' => 'Theo dõi',
            'following' => 'Đang theo dõi',
            'followers' => 'Người theo dõi',
            'no_followers' => 'Chưa có người theo dõi.',
            'text_posts' => 'Bài viết',
            'view_profile' => 'Xem hồ sơ',
            'map_view' => 'Xem bản đồ',
            'list_view' => 'Xem danh sách',

            'add_friend' => 'Kết nối',
            'pending' => 'Đang chờ',
            'accept' => 'Chấp nhận',
            'decline' => 'Từ chối',
            'remove_friend' => 'Xóa khỏi mạng lưới',
            'friend_requests' => 'Yêu cầu kết nối',
            'no_friends' => 'Mạng lưới trống. Hãy khám phá cộng đồng!',

            'send_message' => 'Gửi tin nhắn',
            'type_message' => 'Viết tin nhắn của bạn...',
            'send' => 'Gửi',
            'conversations' => 'Cuộc trò chuyện',
            'no_messages' => 'Chưa có cuộc trò chuyện nào.',
            'invitation_sent' => 'Yêu cầu kết nối đã được gửi kèm tin nhắn.',
            'must_connect_first' => 'Bạn cần kết nối để trao đổi thêm. Hãy chờ xác nhận.',
            'new_conversation' => 'Cuộc trò chuyện mới',

            'feed_title' => 'Bảng tin',
            'write_post' => 'Chia sẻ điều gì đó với cộng đồng...',
            'publish' => 'Đăng',
            'no_posts' => 'Chưa có bài đăng nào. Hãy là người đầu tiên!',
            'new_members' => 'Gợi ý kết bạn',
            'upcoming_events' => 'Sự kiện sắp tới',

            'agenda_title' => 'Lịch của tôi',
            'create_event' => 'Tạo sự kiện',
            'event_title' => 'Tiêu đề',
            'event_desc' => 'Mô tả',
            'event_start' => 'Bắt đầu',
            'event_end' => 'Kết thúc',
            'event_type' => 'Loại sự kiện',
            'event_private' => 'Riêng tư',
            'event_shared' => 'Chia sẻ',
            'event_public' => 'Công khai (hiển thị với mạng lưới)',
            'event_participants' => 'Người tham gia',
            'event_add_participant' => 'Thêm người tham gia',
            'event_busy' => 'Bận',
            'no_events' => 'Không có sự kiện nào.',
            'delete_event' => 'Xóa',
            'event_pending' => 'Lời mời đang chờ',
            'event_accepted' => 'Đã chấp nhận',
            'event_refused' => 'Đã từ chối',
            'accept_event' => 'Chấp nhận',
            'decline_event' => 'Từ chối',

            'nav_explore' => 'Khám phá',
            'nav_learn' => 'Học hỏi',
            'nav_community' => 'Cộng đồng',
            'nav_profile' => 'Hồ sơ',
            'nav_about' => 'Giới thiệu',

            'tutorials' => 'Hướng dẫn',
            'tutorials_intro' => 'Khám phá hướng dẫn nghệ thuật được chia sẻ bởi cộng đồng.',
            'tutorials_ex1_title' => 'Màu nước & Hội họa',
            'tutorials_ex1_desc' => 'Học kỹ thuật hội họa được truyền giữa các thế hệ.',
            'tutorials_ex2_title' => 'Nghệ thuật số',
            'tutorials_ex2_desc' => 'Vẽ kỹ thuật số, minh họa, motion design: nghệ sĩ trẻ chia sẻ công cụ.',
            'tutorials_ex3_title' => 'Thủ công & Sáng tạo',
            'tutorials_ex3_desc' => 'Gốm sứ, origami, dệt may: kỹ năng thủ công không có tuổi.',
            'workshops' => 'Xưởng thực hành',
            'workshops_intro' => 'Tham gia xưởng sáng tạo trực tuyến do cộng đồng tổ chức.',
            'workshops_ex1_title' => 'Xưởng phác thảo trực tiếp',
            'workshops_ex1_desc' => 'Mỗi tuần, một nghệ sĩ dẫn dắt phiên vẽ trực tiếp.',
            'workshops_ex2_title' => 'Vòng tròn phê bình nghệ thuật',
            'workshops_ex2_desc' => 'Trình bày tác phẩm và nhận phản hồi từ mọi lứa tuổi.',
            'workshops_ex3_title' => 'Masterclass liên thế hệ',
            'workshops_ex3_desc' => 'Nghệ sĩ kinh nghiệm truyền kỹ thuật cho người mới.',
            'resources' => 'Tài nguyên',
            'resources_intro' => 'Hướng dẫn, công cụ và tài liệu tham khảo nghệ thuật từ cộng đồng.',
            'resources_ex1_title' => 'Hướng dẫn kỹ thuật',
            'resources_ex1_desc' => 'Tài liệu thực hành để tiến bộ trong từng bộ môn.',
            'resources_ex2_title' => 'Công cụ khuyên dùng',
            'resources_ex2_desc' => 'Phần mềm, vật liệu và nền tảng được cộng đồng khuyên dùng.',
            'resources_ex3_title' => 'Phòng trưng bày cảm hứng',
            'resources_ex3_desc' => 'Tác phẩm, bài viết và tài liệu tham khảo giữa các nghệ sĩ.',

            'forum' => 'Diễn đàn',
            'forum_intro' => 'Trao đổi với cộng đồng về mọi chủ đề.',
            'events' => 'Sự kiện',
            'showcases' => 'Trưng bày',
            'showcases_intro' => 'Khám phá tác phẩm và sáng tạo của các thành viên.',
            'coming_soon' => 'Tính năng này sắp ra mắt! Hãy theo dõi.',

            'dashboard' => 'Bảng điều khiển',
            'portfolio' => 'Hồ sơ năng lực',
            'portfolio_hint' => 'Hồ sơ năng lực giới thiệu bộ môn và hành trình nghệ thuật của bạn. Làm phong phú hồ sơ để thu hút thêm kết nối!',
            'settings' => 'Cài đặt',

            'team' => 'Đội ngũ',
            'team_intro' => 'Crilay được thực hiện bởi đội sinh viên quốc tế.',
            'team_dev_title' => 'Phát triển',
            'team_dev_desc' => 'Thiết kế và phát triển nền tảng web.',
            'team_design_title' => 'Thiết kế & Đồ họa',
            'team_design_desc' => 'Nhận diện thương hiệu, giao diện và trải nghiệm người dùng.',
            'team_comm_title' => 'Truyền thông',
            'team_comm_desc' => 'Chiến lược truyền thông và quảng bá dự án.',
            'contact' => 'Liên hệ',
            'contact_intro' => 'Có câu hỏi? Hãy liên hệ chúng tôi!',
            'contact_email_label' => 'Email',
            'contact_discord' => 'Tham gia máy chủ Discord của chúng tôi.',

            'about' => 'Giới thiệu',
            'faq' => 'Câu hỏi',
            'legal' => 'Thông tin pháp lý',
            'cgu' => 'Điều khoản sử dụng',
            'privacy' => 'Chính sách bảo mật',
            'footer_copy' => '© 2026 Crilay. Mọi quyền được bảo lưu.',

            'about_title' => 'Về Crilay',
            'about_text' => 'Crilay là mạng xã hội liên thế hệ cho phép mọi người ở mọi lứa tuổi, mọi quốc gia và mọi nền văn hóa gặp nhau trực tuyến để trao đổi kỹ năng và kinh nghiệm sống. Sứ mệnh: kết nối các thế hệ thông qua chia sẻ kiến thức.',
            'faq_title' => 'Câu hỏi thường gặp',
            'legal_title' => 'Thông tin pháp lý',
            'legal_text' => 'Crilay là dự án giáo dục trong khuôn khổ Hội thảo Quốc tế IOBC 2026. Nhà xuất bản: Đội Crilay IUT de Bobigny, Université Sorbonne Paris Nord.',
            'cgu_title' => 'Điều khoản sử dụng chung',
            'cgu_text' => 'Khi sử dụng Crilay, bạn cam kết: tôn trọng người dùng khác bất kể tuổi tác, văn hóa hay nguồn gốc; không đăng nội dung thù hận, phân biệt chủng tộc, giới tính hay bạo lực; tôn trọng pháp luật nước bạn; sử dụng nền tảng với tinh thần chia sẻ liên thế hệ.',
            'privacy_title' => 'Chính sách bảo mật',
            'privacy_text' => 'Theo quy định GDPR, dữ liệu cá nhân của bạn được lưu trữ an toàn và không bao giờ chia sẻ với bên thứ ba. Địa chỉ email không hiển thị cho người dùng khác.',

            'error_pseudo_taken' => 'Biệt danh này đã được sử dụng.',
            'error_email_taken' => 'Email này đã được sử dụng.',
            'error_password_mismatch' => 'Mật khẩu không khớp.',
            'error_password_short' => 'Mật khẩu phải có ít nhất 8 ký tự.',
            'error_cgu' => 'Bạn phải chấp nhận điều khoản sử dụng.',
            'error_login' => 'Thông tin đăng nhập không chính xác.',
            'error_fields' => 'Vui lòng điền tất cả các trường bắt buộc.',
            'success_register' => 'Chào mừng đến Crilay! Đăng nhập để tham gia cộng đồng.',
            'success_profile' => 'Hồ sơ đã được cập nhật thành công.',
        ];

        $all = ['en' => $en, 'sq' => $sq, 'vi' => $vi];
        self::$traductions = $all[self::$langue] ?? $en;
    }

    public static function t($cle)
    {
        return self::$traductions[$cle] ?? $cle;
    }
}
